export { Header } from './Header';
export { Hero } from './Hero';
export { ClientProfileSection } from './ClientProfileSection';
export { GabrielaSection } from './GabrielaSection';
export { DifferentialsSection } from './DifferentialsSection';
export { TrustSection } from './TrustSection';
export { FAQSection } from './FAQSection';
export { CTAFinalSection } from './CTAFinalSection';
export { Footer } from './Footer';
